name: Publish MILANO NuGet

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore projects
        run: |
          dotnet restore src/MILANO.Common/MILANO.Common.csproj
          dotnet restore src/MILANO.Client/MILANO.Client.csproj

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Pack
        run: |
          dotnet pack src/MILANO.Common/MILANO.Common.csproj \
            -c Release \
            -o ./artifacts \
            -p:Version=${{ steps.version.outputs.VERSION }}

          dotnet pack src/MILANO.Client/MILANO.Client.csproj \
            -c Release \
            -o ./artifacts \
            -p:Version=${{ steps.version.outputs.VERSION }}

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --skip-duplicate